In [1]:
import pandas as pd
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

In [24]:
tables = pd.read_html(url)
tables

[    Symbol                Security SEC filings             GICS Sector  \
 0      MMM              3M Company     reports             Industrials
 1      ABT     Abbott Laboratories     reports             Health Care
 2     ABBV             AbbVie Inc.     reports             Health Care
 3     ABMD             ABIOMED Inc     reports             Health Care
 4      ACN           Accenture plc     reports  Information Technology
 ..     ...                     ...         ...                     ...
 500    YUM         Yum! Brands Inc     reports  Consumer Discretionary
 501   ZBRA      Zebra Technologies     reports  Information Technology
 502    ZBH  Zimmer Biomet Holdings     reports             Health Care
 503   ZION           Zions Bancorp     reports              Financials
 504    ZTS                  Zoetis     reports             Health Care

                       GICS Sub Industry     Headquarters Location  \
 0              Industrial Conglomerates       St. Paul, Minnesota
 1                 Health Care Equipment   North Chicago, Illinois
 2                       Pharmaceuticals   North Chicago, Illinois
 3                 Health Care Equipment    Danvers, Massachusetts
 4        IT Consulting & Other Services           Dublin, Ireland
 ..                                  ...                       ...
 500                         Restaurants      Louisville, Kentucky
 501  Electronic Equipment & Instruments    Lincolnshire, Illinois
 502               Health Care Equipment           Warsaw, Indiana
 503                      Regional Banks      Salt Lake City, Utah
 504                     Pharmaceuticals  Florham Park, New Jersey

     Date first added      CIK      Founded
 0                NaN    66740         1902
 1         1964-03-31     1800         1888
 2         2012-12-31  1551152  2013 (1888)
 3         2018-05-31   815094         1981
 4         2011-07-06  1467373         1989
 ..               ...      ...          ...
 500       1997-10-06  1041061          NaN
 501       2019-12-23   877212         1969
 502       2001-08-07  1136869          NaN
 503       2001-06-22   109380          NaN
 504       2013-06-21  1555280          NaN

 [505 rows x 9 columns],
                    Date  Added                            Removed  \
                    Date Ticker                   Security  Ticker
 0     December 23, 2019    LYV  Live Nation Entertainment     AMG
 1     December 23, 2019   ZBRA         Zebra Technologies    TRIP
 2     December 23, 2019    STE                 STERIS plc     MAC
 3      December 9, 2019   ODFL  Old Dominion Freight Line     STI
 4      December 5, 2019    WRB  W. R. Berkley Corporation    VIAB
 ..                  ...    ...                        ...     ...
 219  September 25, 2003   ESRX            Express Scripts    QTRN
 220    December 5, 2000   INTU                     Intuit      BS
 221    December 5, 2000    SBL        Symbol Technologies      OI
 222    December 5, 2000    AYE           Allegheny Energy     GRA
 223    December 5, 2000    ABK            Ambac Financial     CCK

                                 \
                       Security
 0    Affiliated Managers Group
 1                 Trip Advisor
 2                     Macerich
 3               SunTrust Banks
 4                       Viacom
 ..                         ...
 219    Quintiles Transnational
 220            Bethlehem Steel
 221             Owens-Illinois
 222                 W.R. Grace
 223             Crown Holdings

                                                 Reason
                                                 Reason
 0                     Market capitalization change.[7]
 1                     Market capitalization change.[8]
 2                     Market capitalization change.[9]
 3    BB&T acquired SunTrust to form Truist Financia...
 4           CBS acquired Viacom to form ViacomCBS.[11]
 ..                                                 ...
 219                                 Taken private[189]
 220                           Market Cap changes.[190]
 221                                Market Cap changes.
 222                                Market Cap changes.
 223                                Market Cap changes.

 [224 rows x 6 columns]]

In [4]:
df_500 = tables[0]
df_500

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,NaN

In [9]:
df_500.groupby(['GICS Sector'])['Symbol'].count()

GICS Sector
Communication Services    26
Consumer Discretionary    64
Consumer Staples          33
Energy                    28
Financials                66
Health Care               61
Industrials               70
Information Technology    70
Materials                 28
Real Estate               31
Utilities                 28
Name: Symbol, dtype: int64

In [21]:
realEstate_list = df_500[df_500['GICS Sector']=='Real Estate']['Symbol'].to_list()
communication_list = df_500[df_500['GICS Sector']=='Communication Services']['Symbol'].to_list()
consumerStaples_list = df_500[df_500['GICS Sector']=='Consumer Staples']['Symbol'].to_list()
consumer_list =  df_500[df_500['GICS Sector']=='Consumer Discretionary']['Symbol'].to_list()
energy_list = df_500[df_500['GICS Sector']=='Energy']['Symbol'].to_list()
financials_list = df_500[df_500['GICS Sector']=='Financials']['Symbol'].to_list()
health_list = df_500[df_500['GICS Sector']=='Health Care']['Symbol'].to_list()
industrials_list = df_500[df_500['GICS Sector']=='Industirals']['Symbol'].to_list()
information_list = df_500[df_500['GICS Sector']=='Information Technology']['Symbol'].to_list()
materials_list = df_500[df_500['GICS Sector']=='Materials']['Symbol'].to_list()
utilities_list = df_500[df_500['GICS Sector']=='Utilities']['Symbol'].to_list()

In [22]:
print(realEstate_list)
print(communication_list)
print(consumer_list)
print(consumerStaples_list)
print(energy_list)
print(financials_list)
print(health_list)
print(industrials_list)
print(information_list)
print(materials_list)
print(utilities_list)

['ARE', 'AMT', 'AIV', 'AVB', 'BXP', 'CBRE', 'CCI', 'DLR', 'DRE', 'EQIX', 'EQR', 'ESS', 'EXR', 'FRT', 'PEAK', 'HST', 'IRM', 'KIM', 'MAA', 'PLD', 'PSA', 'O', 'REG', 'SBAC', 'SPG', 'SLG', 'UDR', 'VTR', 'VNO', 'WELL', 'WY']
['ATVI', 'GOOGL', 'GOOG', 'T', 'CTL', 'CHTR', 'CMCSA', 'DISCA', 'DISCK', 'DISH', 'EA', 'FB', 'FOXA', 'FOX', 'IPG', 'LYV', 'NFLX', 'NWSA', 'NWS', 'OMC', 'TMUS', 'TTWO', 'TWTR', 'VZ', 'VIAC', 'DIS']
['AAP', 'AMZN', 'APTV', 'AZO', 'BBY', 'BKNG', 'BWA', 'CPRI', 'KMX', 'CCL', 'CMG', 'DHI', 'DRI', 'DG', 'DLTR', 'EBAY', 'EXPE', 'F', 'GPS', 'GRMN', 'GM', 'GPC', 'HRB', 'HBI', 'HOG', 'HAS', 'HLT', 'HD', 'KSS', 'LB', 'LVS', 'LEG', 'LEN', 'LKQ', 'LOW', 'M', 'MAR', 'MCD', 'MGM', 'MHK', 'NWL', 'NKE', 'JWN', 'NCLH', 'NVR', 'ORLY', 'PHM', 'PVH', 'RL', 'ROST', 'RCL', 'SBUX', 'TPR', 'TGT', 'TIF', 'TJX', 'TSCO', 'ULTA', 'UAA', 'UA', 'VFC', 'WHR', 'WYNN', 'YUM']
['MO', 'ADM', 'BF.B', 'CPB', 'CHD', 'CLX', 'KO', 'CL', 'CAG', 'STZ', 'COST', 'COTY', 'EL', 'GIS', 'HSY', 'HRL', 'SJM', 'K', 'KMB', 'KHC', 'KR', 'LW', 'MKC', 'TAP', 'MDLZ', 'MNST', 'PEP', 'PM', 'PG', 'SYY', 'TSN', 'WMT', 'WBA']
['APA', 'BKR', 'COG', 'CVX', 'XEC', 'CXO', 'COP', 'DVN', 'FANG', 'EOG', 'XOM', 'HAL', 'HP', 'HES', 'HFC', 'KMI', 'MRO', 'MPC', 'NOV', 'NBL', 'OXY', 'OKE', 'PSX', 'PXD', 'SLB', 'FTI', 'VLO', 'WMB']
['AFL', 'ALL', 'AXP', 'AIG', 'AMP', 'AON', 'AJG', 'AIZ', 'BAC', 'BK', 'BRK.B', 'BLK', 'COF', 'CBOE', 'SCHW', 'CB', 'CINF', 'C', 'CFG', 'CME', 'CMA', 'DFS', 'ETFC', 'RE', 'FITB', 'FRC', 'BEN', 'GL', 'GS', 'HIG', 'HBAN', 'ICE', 'IVZ', 'JPM', 'KEY', 'LNC', 'L', 'MTB', 'MKTX', 'MMC', 'MET', 'MCO', 'MS', 'MSCI', 'NDAQ', 'NTRS', 'PBCT', 'PNC', 'PFG', 'PGR', 'PRU', 'RJF', 'RF', 'SPGI', 'STT', 'SIVB', 'SYF', 'TROW', 'TRV', 'TFC', 'USB', 'UNM', 'WRB', 'WFC', 'WLTW', 'ZION']
['ABT', 'ABBV', 'ABMD', 'A', 'ALXN', 'ALGN', 'AGN', 'ABC', 'AMGN', 'ANTM', 'BAX', 'BDX', 'BIIB', 'BSX', 'BMY', 'CAH', 'CNC', 'CERN', 'CI', 'COO', 'CVS', 'DHR', 'DVA', 'XRAY', 'EW', 'GILD', 'HCA', 'HSIC', 'HOLX', 'HUM', 'IDXX', 'ILMN', 'INCY', 'ISRG', 'IQV', 'JNJ', 'LH', 'LLY', 'MCK', 'MDT', 'MRK', 'MTD', 'MYL', 'PKI', 'PRGO', 'PFE', 'DGX', 'REGN', 'RMD', 'STE', 'SYK', 'TFX', 'TMO', 'UNH', 'UHS', 'VAR', 'VRTX', 'WAT', 'WCG', 'ZBH', 'ZTS']
[]
['ACN', 'ADBE', 'AMD', 'AKAM', 'ADS', 'APH', 'ADI', 'ANSS', 'AAPL', 'AMAT', 'ANET', 'ADSK', 'ADP', 'AVGO', 'BR', 'CDNS', 'CDW', 'CSCO', 'CTXS', 'CTSH', 'GLW', 'DXC', 'FFIV', 'FIS', 'FISV', 'FLT', 'FLIR', 'FTNT', 'IT', 'GPN', 'HPE', 'HPQ', 'INTC', 'IBM', 'INTU', 'IPGP', 'JKHY', 'JNPR', 'KEYS', 'KLAC', 'LRCX', 'LDOS', 'MA', 'MXIM', 'MCHP', 'MU', 'MSFT', 'MSI', 'NTAP', 'NLOK', 'NVDA', 'ORCL', 'PAYX', 'PYPL', 'QRVO', 'QCOM', 'CRM', 'STX', 'NOW', 'SWKS', 'SNPS', 'TEL', 'TXN', 'VRSN', 'V', 'WDC', 'WU', 'XRX', 'XLNX', 'ZBRA']
['APD', 'ALB', 'AMCR', 'AVY', 'BLL', 'CE', 'CF', 'CTVA', 'DOW', 'DD', 'EMN', 'ECL', 'FMC', 'FCX', 'IP', 'IFF', 'LIN', 'LYB', 'MLM', 'MOS', 'NEM', 'NUE', 'PKG', 'PPG', 'SEE', 'SHW', 'VMC', 'WRK']
['AES', 'LNT', 'AEE', 'AEP', 'AWK', 'ATO', 'CNP', 'CMS', 'ED', 'D', 'DTE', 'DUK', 'EIX', 'ETR', 'EVRG', 'ES', 'EXC', 'FE', 'NEE', 'NI', 'NRG', 'PNW', 'PPL', 'PEG', 'SRE', 'SO', 'WEC', 'XEL']